SafeFatalIOError: Updated to print correct file and line number Resolves bug-report http://bugs.openfoam.org/view.php?id=2102 Patch contributed by Mattijs Janssens